const sentences = [
    "After blowing fiercely for hours, the hurricane winds at last began to abate.",
    "Harry’s low grades in chemistry are an aberration; he is typically an A student.",
    "For some time now, the dissenters have been held in abeyance; they have suspended all protests.",
    "Once King Edward VIII abdicated the throne to marry a commoner, he abjured all of his former titles.",
    "Years of exposure to the sea spray had abraded the face of the cliffs.",
    "The author recently published an abridged version of his original 600-page novel.",
    "It is unlikely that the senator’s push to abrogate any rights regarding free speech will be supported.",
    "The fugitive absconded to Canada in an attempt to avoid arrest in the United States.",
    "The idea that Samantha would fail her test was completely absurd; she had studied for hours and was completely prepared.",
    "Despite all of the advertisements promoting the new product, its first- quarter sales were abysmal.",
    "Increased organic matter accumulation has led to an increase in the accretion rate in the Mississippi Delta.",
    "The acquisitive nature of the chimpanzee makes it appear almost human.",
    "Sean immediately turned the engine off when he smelled acrid smoke billowing from beneath the hood of his car.",
    "Henry was an acute observer; he quickly learned the rules of the game.",
    "In order to maintain order in his classroom, Mr. Blume required strict adherence to the code of conduct.",
    "Chase took a new job in downtown Chicago, but purchased a house in an adjacent suburb.",
    "Steve was considered an adroit negotiator; he was often able to settle disputes when others had failed.",
    "The aesthetic quality of the painting was more appealing than its historical significance.",
    "Michelle’s affinity for getting straight to the point made her a popular editor at the publishing house.",
    "Gregg often felt alienated from his classmates because of his illness.",
    "The student’s ambiguous answer left the professor wondering whether the student had studied the assigned material.",
    "His inability to show emotion left her feeling ambivalent about their relationship.",
    "Josh was amenable to eating dinner early; he was ravenous.",
    "Joe was very amiable; as a result, he made friends easily at his new school.",
    "Her yearning to be nothing more than a housewife seemed an anachronism in today’s society.",
    "In order to ensure the credibility of his students’ sources, the professor asked the students to annotate their bibliographies.",
    "The botanists were excited when they discovered the unique flower; it was a complete anomaly.",
    "Mary appeared quite apathetic at her trial; she seemed unconcerned by the jury’s guilty verdict.",
    "Scott’s ardor for Julianne increased as he spent more and more time with her.",
    "Young children often find it difficult to articulate exactly what they are thinking.",
    "It is not unusual to ascribe jealousy and pettiness to one’s critics.",
    "The asperity of the desert climate in Death Valley prevents many people from visiting for extended periods of time.",
    "The diplomat carefully assayed the situation prior to making a decision.",
    "It is often necessary for a parent to assert his or her authority over an unruly child.",
    "The journey to earning good grades is an assiduous one; consistent effort must be put forth.",
    "Many immigrants desire to assimilate quickly into their new community.",
    "Mandy often used food to assuage her loneliness, a habit that led to her problem with obesity.",
    "Because Jennifer wore glasses every day, we assumed that she had poor eyesight.",
    "The politician continued to aver that he was more experienced than his opponent, despite evidence to the contrary.",
    "Kelly has such an aversion to strenuous exercise that she never goes to the gym.",
    "The deposed dictator was banished from his native country.",
    "Mr. Horn’s benevolence made him a beloved school principal; his generosity and understanding far exceeded that of his predecessor.",
    "Katherine was relieved to discover that her tumor was benign; she would not require surgery after all.",
    "This collection of rare manuscripts was donated to the library as a bequest from Professor Austin.",
    "Jill was bereft when she discovered that the coveted role had been offered to another actress.",
    "Ellen’s blithe and outgoing attitude made her one of the most popular students on campus.",
    "The small business owner secured a low-interest loan to bolster his financial situation during a period of expansion.",
    "His often brazen behavior at work led to his being reprimanded on a regular basis.",
    "Although it was completely undeveloped a year ago, the vacant land is now home to a burgeoning commercial area, complete with a new shopping mall.",
    "The destitute man was relegated to cadging meals from local restaurants.",
    "Jill’s sudden move to Hollywood was considered capricious by the rest of her family.",
    "Jason was castigated by his teacher for turning in his assignment late.",
    "Our classmate’s recent job offer served as a catalyst for the rest of us to update and submit our resumes.",
    "The prosecuting attorney was censured for a conflict of interest arising from his personal relationship with the plaintiff.",
    "Several biographers have chronicled the life of Albert Einstein, one of the world’s greatest physicists.",
    "A wise investor is circumspect about fluctuations in the market.",
    "The company cited a 10 percent increase in sales as evidence that their new advertising campaign was achieving the predicted results.",
    "The different factions coalesced to form a strong group opposed to the current regime.",
    "The jury did not hear the man’s taped confession during the trial because police had coerced him into admitting that he had committed the crime.",
    "The teenager’s cogent argument for a later curfew persuaded his parents to push it back to midnight.",
    "Entering college at the age of 14, the teen had cognitive abilities far beyond most of her peers.",
    "The essay lacked coherence; it did not flow logically from one concept to the next.",
    "The coincidental meeting of two old friends was a pleasant surprise for them both.",
    "He refused the job offer; the salary did not seem commensurate with his related skills and experience.",
    "Eager to earn a large tip, our waiter was unusually complaisant.",
    "Students enrolled in the music program comprised the university marching band.",
    "The presidential candidate decided to concede defeat based on the latest poll results; he was too far behind to win.",
    "The noisy restaurant was not conducive to holding intimate conversations.",
    "To her consternation, she found that she’d forgotten to bring her assignment to class.",
    "Ambulances, police cars, and fire trucks quickly converged on the scene of the accident.",
    "There was always a convivial atmosphere at the annual holiday party.",
    "According to researchers, the length of time a student studies is roughly correlated to the grades that the student receives.",
    "Further laboratory tests corroborated the scientist’s theory that taking vitamins could help to maintain a person’s good health.",
    "The teacher had a stern countenance that intimidated many of her students.",
    "Even the most credulous person would not believe the story that Mike had concocted.",
    "The cryptic hieroglyphics on the Rosetta Stone were finally deciphered using the Greek writings also found on the stone.",
    "Finishing the marathon in less than four hours was the culmination of months and months of training for Elaine.",
    "Despite his claims to the contrary, the senator is likely culpable of misappropriating funds.",
    "Bob’s broken leg left him debilitated and unable to attend school.",
    "The rain forest is being decimated at an alarmingly fast pace; it is estimated that it could be completely gone within 40 years.",
    "A loyal fan of classical music, Megan decried all popular rap and hip-hop artists.",
    "The celebrity sued the tabloid for defamation of character when the magazine published a story filled with lies.",
    "Many philosophers and scientists delve into the secrets of the universe.",
    "The demise of the dinosaurs is a topic of much debate among paleontologists.",
    "You should not denigrate a person whose opinion differs from yours.",
    "Many people disapprove of how Native Americans are depicted in old Westerns.",
    "Environmental advocacy groups deplore deforestation and industrial pollution.",
    "Joe’s harsh derision of his pesky younger brother set everyone on edge at the dinner table.",
    "There are zero-calorie sweeteners available that are derivatives of real sugar.",
    "The project leader’s rather desultory speech left the team members uncertain of how to proceed.",
    "It took great dexterity, but the politician managed to evade answering every difficult question that the reporters threw at him.",
    "The environmental activist launched into a lengthy diatribe against the developers who wanted to build a new mall in place of the city park.",
    "Professor McFarland’s didactic presentations in the classroom tended to bore some students and outrage others.",
    "Jesse’s pupils began to dilate as the sun set and the room darkened.",
    "Ben diligently trained for the marathon, running at least 40 miles per week.",
    "I hope that this most recent scandal will finally disabuse the public of its notion that the senator is infallible.",
    "The moon’s distance from Earth makes it difficult to discern most of the features on the surface of the moon with the naked eye.",
    "Linda had the disconcerting habit of staring at the ground whenever she spoke.",
    "The small earthquake dislodged several tons of rock from the mountain.",
    "There was much disparity between my perception of the judicial process and the actual manner in which the process worked.",
    "The crowd began to disperse as the concert came to an end.",
    "The platoon’s efforts to dissemble their preparations resulted in a swift ambush of the enemy the following day.",
    "It took hours of careful diplomacy for the staunch political dissidents to reach an accord.",
    "The wind helped to dissipate the smoke from our campfire.",
    "Band leaders know immediately by the piercing dissonance that a wrong note has been played.",
    "Though they agreed on most things, their opinions diverged on the topic of abortion rights.",
    "Howard was extremely lucky; he divested himself of $10 million worth of electronics stock days before its value plummeted.",
    "The normally docile students became very rowdy as the day’s pep rally drew near.",
    "Mike was very dubious when his older brother, infamous for playing pranks, told Mike that he had a surprise for him.",
    "Mary’s style, considered to be very eccentric when she was young, led her to become one of the most popular fashion designers of all time.",
    "Jenny’s eclectic taste in movies ranged from musicals to comedies, dramas to action films.",
    "The general was unaware that his imperialist effrontery was only breeding contempt among the colonists.",
    "William committed an egregious error when he failed to mention his wife during his acceptance speech.",
    "Julie’s valedictorian speech was quite eloquent; she clearly articulated her hopes and dreams for a prosperous future.",
    "Recent efforts to elucidate the text on certain ancient scrolls have yielded curious new perspectives on the political history of Babylon.",
    "Minor children may petition a court for emancipation from their parents if they provide evidence of alternate housing and income.",
    "Sarah rubbed an emollient over her dry, peeling, sunburned skin.",
    "The hypothesis had to be backed up by empirical evidence in order to be considered credible.",
    "As she entered law school, she hoped to emulate the success of her sister, who was already a prominent partner in a law firm.",
    "The sports superstar was paid more than $10 million to endorse the new athletic shoe.",
    "Professor Evan’s good nature engendered a positive attitude among his students.",
    "Though the corporations worked in conjunction with each other, they remained separate legal entities.",
    "At his performance review, the employee listened to his boss enumerate several ways he could improve his performance in the workplace.",
    "Considered a “one-hit wonder,” the pop star enjoyed only ephemeral fame.",
    "Many lengthy court battles could be avoided if the legislature took more care to avoid equivocal language in the criminal statutes.",
    "After earning three doctoral degrees, Dr. Kidman was considered one of the most erudite professors on campus.",
    "Most of the subject matter in the novel is quite esoteric; the author is forced to overwhelm the reader with too much background information.",
    "Abraham Lincoln was famous for his refusal to espouse slavery in the North.",
    "His first attempt at writing a novel was estimable; nearly 1 million copies of the book were sold.",
    "Only the most ethical people would return money from a wallet they find in the street.",
    "The word borrowing is sometimes used as a euphemism for stealing.",
    "The terrorist attacks exacerbated the already strained relations between the two countries.",
    "Kevin was an exceptional basketball player, and received many offers to play at the collegiate level.",
    "The film critics excoriated the film that was supposed to be that year’s biggest blockbuster, emphasizing how overrated it was.",
    "The defendant was exculpated of the homicide charges when new evidence was found at the crime scene.",
    "After graduating from college, Diana exhorted her parents to lend her the money to start her own business.",
    "In the exigent circumstances of the coup d’état, thousands of troops were dispatched to the capital city.",
    "The graduate student was unable to successfully explicate his thesis; therefore, he did not earn his degree.",
    "The speeding infraction would be expunged from John’s driving record after he paid a $600 fine and kept a clean record for one year.",
    "There are few extant copies of the Gutenberg Bible, four of which are in New York City.",
    "Extenuating circumstances surrounding the motive for the assault meant Sean would serve less jail time.",
    "Ever the proud mother, Anna extols her child’s accomplishments to no end.",
    "In order to be successful as a salesperson, you must be somewhat of an extrovert.",
    "It took rescue crews several hours to safely extricate all of the passengers from the plane that had crashed earlier in the day.",
    "The exultant crowd cheered the soccer team on to victory in the World Cup.",
    "It is a common fallacy that first-year law students spend every waking moment studying.",
    "Her familial ties kept her from moving too far away from the town in which she grew up.",
    "The complexity of the situation made it difficult to fathom a simple outcome.",
    "We ignored Brendan’s fatuous remarks about politics; he spoke strictly from opinion with no regard for the facts.",
    "Because more than half of the legislators are not running for reelection this fall, pundits predict another feckless session of the State House.",
    "She feigned astonishment when she walked into her surprise party; her best friend had previously told her about the event.",
    "The robbers used some smoke bombs in the parking lot as a feint while they discreetly took money from the cash drawers.",
    "I admire dogs for their unshakeable fidelity to their owners.",
    "The stark realism of neoclassicism in painting replaced the florid idealism of the Rococo period.",
    "Her plans were often foiled by her failure to plan ahead.",
    "Ryan tried to hold his tongue; he knew that one of his sarcastic remarks would foment a fight that he didn’t want to start.",
    "During the cold winter months, many wild animals are forced to forage for scarce food.",
    "The current championship team was a formidable opponent for the yet unranked team.",
    "The defenseman scored easily with a quick shot after the puck’s fortuitous bounce toward him.",
    "The mayor held an open forum for discussion to learn what the people thought of his new proposal.",
    "James was arrested for disorderly conduct after getting into a fracas outside the restaurant this weekend.",
    "There can be no resolution if all you do is gainsay each of my suggestions.",
    "The garrison was currently home to nearly 400 troops.",
    "The normally garrulous teenager was very subdued at the party; she barely spoke to anyone.",
    "His favorite genre of music was classic rock, but he also enjoyed jazz quite a bit.",
    "I’m in a hurry, so please tell me the gist of the story.",
    "The president’s glib speech about the financial state of the company resulted in a general sense of unease among the members of the staff.",
    "Her gratuitous acts of kindness earned her fondness and respect within the community.",
    "It’s a wonder Lynn can get a word in edgewise when speaking with her extremely gregarious sister.",
    "The spokesperson knew he had made a grievous error when he prematurely announced that all of the victims had survived the accident.",
    "I employed all of my guile to convince my housemates that I truly deserved the largest bedroom in the house along with the house’s single parking spot.",
    "The hackneyed plot of the television show led to its cancellation after only three episodes.",
    "The prospect of a beach landing in broad daylight harrowed the troops for days before the battle.",
    "The business’s hierarchy allowed room for all employees to advance within the company if they worked hard enough.",
    "Switzerland has a heterogeneous culture, in which German, French, and Italian influences are intermixed.",
    "The graduate students working on the project presented a viable hypothesis regarding the outcome of their experiments.",
    "One of the most annoying idiosyncrasies of the computer is that it must be completely restarted every two hours.",
    "People should know that their freedom is not immutable and must be protected whenever necessary.",
    "We changed our tee time to later that afternoon because of the impending rain.",
    "Kevin’s imperturbable demeanor during the storm helped keep his wife and children calm.",
    "The upcoming race provided the impetus she needed to expand her training regimen.",
    "A careful implosion of the old stadium would prevent damage to adjacent structures and onlookers.",
    "His inadvertent pull of the lever started a chain reaction of leaks throughout the building’s plumbing.",
    "His inchoate political opinions were based largely on ignorance.",
    "The leaves were incinerated quickly in the raging campfire.",
    "Carrie’s colorful joke was incongruous with the deep conversation going on around her.",
    "The child was incorrigible; he refused to listen when his parents repeatedly told him to stop teasing the dog.",
    "The Maori are the indigenous people of New Zealand.",
    "After spending the weekend doing everything but studying, it was inevitable that she would fail her exam.",
    "Mr. Mauro was able to infer from his employee’s attitude that she was not satisfied with her job.",
    "The world relies on the ingenuity of people such as Bell and Edison to conceive of tomorrow’s technology.",
    "The risks inherent in driving a car are surprisingly greater than those associated with riding in an airplane.",
    "Doctors agree smoking is inimical to good health and longevity.",
    "Linguists still don’t know why humans have an innate capacity for language while other animals do not.",
    "Science still has little explanation for the inscrutable origins of matter and energy in the universe.",
    "Andrew attempted to insinuate himself into the conversation by replying to a question that was not directed at him.",
    "Waiting in line for the movie, I was forced to listen to an insipid conversation between two young girls who could not decide which actor they found most attractive.",
    "The villagers displayed the typical insularity of small communities.",
    "The quarterback was an integral part of the football team’s seven-game winning streak.",
    "When Kelly learned that she had become the prime suspect in a police investigation, she called upon her lawyer to intercede.",
    "No one can be sure what fanciful stories were interpolated into the old chronicle by medieval scribes.",
    "Paul’s intractable temper landed him in jail after a brief altercation with a police officer.",
    "The government was inundated with requests for help after the hurricane destroyed or damaged over 10,000 homes and businesses.",
    "Every winter it snows heavily in this area, but by now I am inured to the harsh climate.",
    "Judge Owens is famous for his invariable demeanor, which is lauded by prosecution and defense counsel alike.",
    "Grizzly bears are irascible beasts, which one would do well to avoid.",
    "Noelle was in a jovial mood for weeks after getting engaged to her high school sweetheart.",
    "Kate’s decision not to take the job was quite judicious because she had no previous marketing experience.",
    "The artist juxtaposed some of his early sketches with some of his later works to show how much his style had changed over time.",
    "His keen sense of smell allowed him to figure out what was for dinner long before he reached the kitchen.",
    "The volunteers all received kudos for their work at the homeless shelter.",
    "The critics lambasted the author’s newest novel, saying he had become lazy in the wake of his last book’s success.",
    "The convict had been languishing in prison for nearly 20 years.",
    "My parents offered either to buy me a new computer or to pay for a trip to Europe for my graduation, and I chose the latter, having never been abroad.",
    "Jenny’s efforts to raise money for breast cancer research were laudable.",
    "He showered her with lavish gifts of jewelry and clothes in an attempt to win her over.",
    "Sarah’s parents were not lenient at all when it came to grades; she was expected to earn straight A’s.",
    "Linda was lethargic all day; she had not slept at all the night before.",
    "During his long illness, Michael became very listless and spent most of his time in bed.",
    "His loathsome behavior ultimately resulted in his being fired; his employers had received numerous complaints from his coworkers.",
    "My plans for a quiet dinner were disrupted by a loquacious patron seated at the next table.",
    "The speaker presented a series of lucid arguments in favor of the antismoking law.",
    "Mark’s ludicrous budget estimations resulted in large financial losses for his company.",
    "Coach Davis was magnanimous in defeat and congratulated the winning team on a game well played.",
    "The villain in the movie was a malevolent old man who would stop at nothing to gain power over the citizens in his community.",
    "The airline workers’ dissatisfaction with their wages manifested itself as a two-week-long strike.",
    "The surface of the antique table was marred during the move from the storage facility.",
    "Reid attributed his melancholy mood to the weather; it had been raining for nearly a week.",
    "“I’m never talking to you AGAIN!” she exclaimed melodramatically to her sister.",
    "Michael had a very mercurial temperament; he could go from cheerful to irate in a matter of moments.",
    "The new CEO vowed that the struggling business would undergo a complete metamorphosis, and that it would soon be thriving and successful.",
    "Janine was meticulous about her appearance, refusing to be seen in public without makeup.",
    "The troops showed their mettle in the face of armed combat.",
    "The acceptable error for this test is minuscule, so the research team takes the utmost care in executing it.",
    "In typical fairy tale style, the heroine of the story overcomes the local miscreant, teaching him a lesson and earning the esteem of the townspeople.",
    "The County Road Commission authorized the use of extra snowplows to help mitigate the hazardous road conditions.",
    "The experienced referees attempted to mollify the angry players before a fight broke out.",
    "The soup kitchen was able to feed more than one thousand homeless people every day, thanks to the munificence of the community.",
    "Brett’s nascent career in politics ended before it began when the public learned that he had been arrested for the purchase of narcotics.",
    "His often negligent behavior led to his being replaced by a more diligent manager.",
    "The difference between the two brands of baby food was negligible; both offered the same nutritional value.",
    "Every time I hear that song, I feel a wave of nostalgia for my college days.",
    "Environmentalists protested the construction of a new factory that would emit large quantities of noxious gases into the atmosphere each day.",
    "The governor was obdurate in her beliefs that schools needed additional funding for their art and music programs.",
    "The 1962 hit single propelled him from relative obscurity in the Canadian north to fame and fortune in Los Angeles.",
    "Telegrams became obsolete with the development of the Internet.",
    "My law professor insinuates that his students are incredibly obtuse if they don’t know the answer to one of his questions.",
    "The brand-new underpass obviates the railroad crossing gates at the intersection.",
    "The odious crimes committed by the gang members put them at the top of the city’s most-wanted list.",
    "The police had the onerous task of somehow convincing the assailant to set his hostages free.",
    "Coworkers have ostracized the young welder since he first spoke out against the union.",
    "It was a strange paradox that adding more capacity to the network actually reduced its overall performance.",
    "Mother Theresa was a paragon of piety and generosity.",
    "Mrs. Antoinette assigned our French class 100 sentences to parse into subject, verb, and tense.",
    "My history teacher’s hopelessly pedantic lectures left the class in a state of utter boredom.",
    "Her penchant for designer clothes was something that her meager salary could simply not support.",
    "Perceiving the sadness in his voice, I asked him if anything was wrong.",
    "Mountain spring water is generally safe to drink because it has spent decades slowly percolating through porous layers of rock.",
    "My grandmother loves to hear stories from the peripatetic salespeople who occasionally come to her door.",
    "Paul jogged daily along the periphery of the lake, enjoying the view of the water as he worked out.",
    "Witnesses whose intent is to deceive the court with their testimony may later be found guilty of perjury.",
    "That a high grade point average leads to a high standardized test score is a myth perpetuated among some educators.",
    "Our professor warned us to read chapter eight very carefully; the information was pertinent to what would be found on our exam.",
    "Each day Liz perused the want ads in the newspaper, desperately trying to find a job.",
    "Because we lived on a farm, it was impossible to avoid the pervasive smell of cow manure at certain times during the year.",
    "Many cosmological phenomena have yet to be fully explained.",
    "Politicians seem to have a knack for obscuring the pith of an issue.",
    "The waitress tried to placate her angry patron by offering him a free meal.",
    "place to get away from it all.",
    "The journalist was sued for plagiarizing an article from another writer and selling it to a national magazine.",
    "Her reasons seemed highly plausible; nonetheless, her friends found it hard to accept her unusual tardiness.",
    "The library has a plethora of books on the Civil War.",
    "The audience sat stunned, moved to silence by the speaker’s poignant remarks.",
    "The novel was based on the ironic polarity of the identical twins.",
    "Karl Marx postulated that Communism was the only successful way to organize the economy; he was wrong.",
    "She was pragmatic in her approach to applying for the job; she thoroughly researched the company prior to her interview.",
    "Many start-up companies find themselves in a very precarious position when seeking additional funding.",
    "The student broke her family’s long-running precedent and attended the University of Colorado instead of Colorado State.",
    "The fraternity’s founding precepts were love and equality among all of its brothers.",
    "The bombings precipitated a massive wave of antiterrorism among the people of the target country.",
    "John’s embezzlement conviction precluded him from getting another high- powered accounting job.",
    "The peasant uprisings of earlier decades are now considered to be precursors of the French Revolution.",
    "Some sailors believe that a red sky in the morning is a presage of storms coming that day.",
    "The captain’s prescience for trouble at sea prompted him to replace the old life jackets he had on board.",
    "Many college graduates with high grade point averages presume that finding employment will be easy.",
    "It was obvious that Emily was prevaricating when her story changed slightly every time she told it.",
    "It is important that those working at the clothing store display probity, for it would be far too easy for greedy employees to take whatever they wanted from inventory.",
    "Gone are the days of prodigal expenditures on social services by the government.",
    "After her foolish mistake, Maria offered profuse apologies.",
    "My great-grandfather is proud of his extensive progeny.",
    "The economic prognosis was bleak; it looked like the recession had only just begun.",
    "Computers, like any other technology, proliferate rapidly as production costs decrease and materials availability increases.",
    "At the Board meeting, the town trustees promulgated some new zoning regulations.",
    "The newly introduced plant species began to propagate quickly in the humid environment.",
    "The prototypes of countless sports cars will be debuted at the auto show next week.",
    "Our train trip was annoyingly protracted by a series of unexplained delays.",
    "Chandler’s athletic prowess was overshadowed by that of his legendary older brother, who was named MVP all four years of his high school football career.",
    "My prudish mother wouldn’t allow me to wear miniskirts, no matter how hot it got in the summer.",
    "After a long day at work, Chad quaffed multiple beers while waiting for his dinner.",
    "The losing candidate’s querulous remarks regarding his opponent were not included in the newspaper article.",
    "The quixotic nature of the weather in April requires that you carry an umbrella with you wherever you go.",
    "Cell phone use has become a quotidian part of our existence; it’s hard to imagine that only 20 years ago cell phones were used primarily in emergencies.",
    "The prisoner’s rancor was increasingly evident in his malicious glance at the warden.",
    "Joanna seemed to morph overnight from a polite child to a recalcitrant teen.",
    "Although the movie star has been in countless blockbusters, she lives as a recluse and refuses to give interviews or appear at publicity events.",
    "You are certainly entitled to some recompense after all of your hours of hard work.",
    "It took hours of negotiations to bring about reconciliation between the two parties.",
    "Many students feel it is more helpful to read the textbook than attend the professor’s recondite lectures.",
    "The testimony provided by the prosecution’s star witness refuted the statements previously made by the defendant.",
    "The journalist was relegated from investigative reporting to writing obituaries after submitting too many substandard articles.",
    "Because of the scandal, the senator renounced all ties to the disgraced lobbyist.",
    "Some countries were unable to pay the reparations demanded after the war.",
    "Zach’s wife reproached him for spending all of his time watching sports on TV.",
    "Ellen repudiated the accusation that she had cheated in order to pass her exam last week.",
    "Kelly is resolute in her decision to run a marathon this year, despite her current inability to run more than one mile without a break.",
    "The resonant voices of the choir rang out through the concert hall.",
    "The bride looked absolutely resplendent walking down the aisle in her white gown.",
    "Each summer, Renaissance festivals try to resurrect the spirit of the Middle Ages across the country.",
    "The politician used his rhetoric to be voted into office, but whether he will actually use his power constructively remains to be seen.",
    "The nature of the study demanded extreme rigor in setting up the experiments.",
    "It is not wise to disobey the teachings of the tribal sages.",
    "After a few years, the sanctimonious preacher was finally exposed and run out of town.",
    "Our research proposal received official sanction from the university last week.",
    "Television shows such as Saturday Night Live satirize many people and current events.",
    "In spite of the declining poll numbers, the senator’s campaign manager remained sedulous to the end.",
    "Miranda’s claims to be a psychic were met with skepticism by her friends and family.",
    "Paul sought solace from the cold near the roaring fireplace in his living room.",
    "For a week after my surgery, my solicitous neighbors brought me meals so I wouldn’t have to cook.",
    "Despite sounding credible, all of Jordan’s arguments were specious.",
    "The tabloids have been speculating for months that the celebrity couple is getting a divorce.",
    "Charlotte’s spontaneous laughter caused an uncomfortable pause in the conversation; nothing that had been said was meant to be funny.",
    "The dictator squelched any sign of rebellion by making it public that those who spoke out against him would be jailed indefinitely.",
    "Carrie pressed a towel firmly onto the wound to stanch the flow of blood.",
    "The typically static price of corn rose dramatically when a major drought hit the Midwest and millions of acres of crops were lost.",
    "Samantha’s two-year stint as a court reporter was one of the most fascinating jobs she ever held.",
    "Kevin’s stoic expression gave no clue about what he was thinking.",
    "I think that my best friend is the greatest actress in the world, but my opinion of her is rather subjective.",
    "I had to provide a list of all sources used in my research paper to substantiate the fact that I didn’t plagiarize.",
    "The new Corporate Policy Manual now subsumes both the Customer Contact Manual and the Internal Procedure Manual.",
    "My desire to go to class was subverted by my body’s need for more sleep.",
    "The farmer donated his crop surfeit to a charity dedicated to feeding the poor.",
    "People who don’t wash their hands frequently are much more susceptible to illnesses than are those people who regularly wash their hands.",
    "The lights in the show were synchronized with the pulsing rhythm of the music.",
    "With a smile, Rob’s girlfriend implied tacit approval of his gift of a dozen roses.",
    "When the constitutional prohibition of alcohol was lifted, citizens were left to manage their own temperance.",
    "My sister has a tenuous grasp of physics; she does not completely understand how the physical world works.",
    "No amount of incentives or creature comforts could lift the cloud of torpor that had overcome the office.",
    "Salespeople tend to tout the obvious benefits of a product, while distracting from any negative aspects of ownership.",
    "Teachers are charged with the powerful task of molding tractable young minds.",
    "Through luck and hard work, he was able to transcend his humble origins.",
    "Joel has repeatedly transgressed the laws against using a cell phone while driving.",
    "When I copied down her telephone number, I foolishly transposed two digits.",
    "The detectives needed more than four hours to extract the unalloyed version of events from the witness.",
    "When the high school principal failed to respond to numerous requests for more information, the school board unilaterally terminated his contract.",
    "The coffee shop franchise launched new locations at an unprecedented rate, opening an average of eight new stores per day across the country.",
    "Sometimes the boss’s unstinting praise of our work can be construed as disingenuous.",
    "Cindy’s urbanity was apparent in the way she dressed herself—classic clothes with a touch of style.",
    "The workers’ coveralls were very utilitarian, but had no regard at all for style or looks.",
    "In an emergency situation there is no time to vacillate, so first responders are taught appropriate courses of actions for a myriad of crises.",
    "Calico cats have variegated coats of many shades of brown, tan, black, and white.",
    "In spite of vehement protests from his parents, Joey left Harvard and moved to Los Angeles to become an actor.",
    "The success of mafia crimes relies on a steady supply of venal police officers and judges.",
    "Dr. Sanford, a most venerable professor, received a standing ovation at his retirement party.",
    "The veracity of his alibi was questioned when several witnesses saw him fleeing the scene of the crime.",
    "Most students were yawning and half-asleep by the end of the dean’s verbose commencement speech.",
    "Carol added several specific details to her story to lend it verisimilitude.",
    "After months of privation in the wilderness, the Andersons enjoyed a veritable feast of turkey, mashed potatoes, stuffing, and carrot cake.",
    "She is a very versatile singer and is equally comfortable singing operatic arias or country-western ballads.",
    "She was vilified in the press as “the other woman” in the divorce case of a married actor.",
    "The suspect was vindicated when the person who actually committed the robbery turned himself in.",
    "Surviving a plunge over Niagara Falls in a barrel was virtually impossible prior to the invention of reliable foam padding and rigid plastics.",
    "The senator condemned and vituperated his political opponents in a series of angry speeches.",
    "He produced a voluminous amount of published works during his 50 years as an author.",
    "After his two-week wilderness camping trip, Pat had a voracious appetite.",
    "Randy’s interest in his baseball card collection began to wane as he got older.",
    "Emily threw a wary glance at the man who had been following her for nearly five blocks.",
    "Before a large meal, I like to whet my appetite with a little wine and cheese.",
    "The wily salesperson convinced my friend to purchase a car that was well beyond my friend’s financial means.",
    "Before traveling abroad, I had a xenophobic mistrust of all people who weren’t American.",
    "As a dedicated and honest attorney, Kara remained committed to the zealous pursuit of the truth.",
    "Winning the Academy Award for Best Actor was the zenith of the actor’s career.",
];

definitions = [
    "Abate: to reduce or lessen",
    "Aberration: a deviation or departure from the norm",
    "Abeyance: temporary inactivity or suspension",
    "Abjure: to forswear or abstain from; to give up",
    "Abrade: to wear down or rub away the surface of something",
    "Abridge: to reduce the length of or diminish in scope (for example, written text)",
    "Abrogate: to end or do away with something",
    "Abscond: to withdraw and hide, typically to avoid arrest",
    "Absurd: extremely ridiculous or completely lacking reason",
    "Abysmal: very profound or deep; very bad",
    "Accretion: a gradual increase in the amount or size of something",
    "Acquisitive: characterized by a strong desire to gain or retain information or objects",
    "Acrid: harsh or bitter taste or smell",
    "Acute: quick and precise, intense; sharp, keen",
    "Adhere: to stick fast; to remain in support of",
    "Adjacent: in the nearest position; next to",
    "Adroit: showing skill and experience",
    "Aesthetic: appealing to the senses because it is beautiful",
    "Affinity: natural attraction; inherent similarity",
    "Alienate: to isolate oneself from others or another person from oneself",
    "Ambiguous: unclear or capable of having more than one meaning",
    "Ambivalent: characterized by uncertainty; unable to decide between opposites",
    "Amenable: responsive to suggestion; willing",
    "Amiable: friendly and pleasant",
    "Anachronism: something existing or happening out of its time in historical order",
    "Annotate: to provide with extra notes or comments",
    "Anomaly: something that is different from the norm",
    "Apathy: a lack of any emotion or concern",
    "Ardor: intense feelings; passion",
    "Articulate: v. to clearly explain. adj. the quality of being able to speak clearly",
    "Ascribe: to attribute to a specific source; to assign a characteristic",
    "Asperity: roughness or severity",
    "Assay: n. an analysis or examination. v. to subject to analysis; to examine",
    "Assert: to demonstrate power; to defend a statement as true",
    "Assiduous: characteristic of careful and persistent effort",
    "Assimilate: to incorporate into; to make similar",
    "Assuage: to lessen or ease",
    "Assumption: something believed to be true without proof; unstated evidence.",
    "Aver: to declare as true; to maintain",
    "Aversion: strong dislike",
    "Banish: to force to leave",
    "Benevolence: an inclination to be kind or charitable",
    "Benign: kind, mild, harmless",
    "Bequest: the act of passing on; something that is passed on",
    "Bereft: deprived or despondent",
    "Blithe: carefree or joyous; casual",
    "Bolster: n. a narrow cushion. v. to support or strengthen",
    "Brazen: bold or shameless; insolent",
    "Burgeoning: thriving or growing rapidly",
    "Cadge: to beg",
    "Capricious: impulsive; prone to sudden change",
    "Castigate: to punish or criticize severely",
    "Catalyst: something that causes something else to happen, usually without being directly involved in or changed by the process; a trigger for an event",
    "Censure: n. a formal criticism or intense disproval. v. to express a formal criticism",
    "Chronicle: n. a detailed narrative. v. to document or record",
    "Circumspect: mindful of potential consequences; prudent",
    "Cite: to quote as an example or proof",
    "Coalesce: to unite or come together",
    "Coerce: to force or threaten someone into acting a certain way; to compel",
    "Cogent: convincing and reasonable",
    "Cognitive: relating to conscious intellectual activity such as thinking, reasoning, and learning",
    "Coherence: the quality of being logical and clear",
    "Coincidental: occurring by chance",
    "Commensurate: corresponding in size, degree, or duration",
    "Complaisant: showing a willingness to please; obliging",
    "Comprise: to consist of; to include",
    "Concede: to admit or reluctantly yield; to surrender",
    "Conducive: contributive; favorable",
    "Consternation: alarm or fear",
    "Converge: to meet or come together at a common point",
    "Convivial: festive and sociable",
    "Correlate: to have corresponding characteristics",
    "Corroborate: to confirm, to substantiate with evidence",
    "Countenance: n. facial features or expression.",
    "Credulous: easily deceived; believing too readily",
    "Cryptic: mystifying; hidden or concealed meaning",
    "Culmination: completion or climax",
    "Culpable: deserving of blame; guilty",
    "Debilitate: to weaken or impair",
    "Decimate: to destroy large numbers of; to inflict great damage upon.",
    "Decry: to denounce or criticize",
    "Defamation: a malicious or abusive attack on one’s character",
    "Cordial: friendly; gracious",
    "Demise: the end of existence; death",
    "Denigrate: to speak ill of; to belittle",
    "Depict: to represent or describe",
    "Deplore: to condemn; disapprove of or regret",
    "Derision: use of ridicule to show contempt",
    "Derivative: adj. copied or adapted. n. something derived",
    "Desultory: inconsistent and irregular, aimless",
    "Dexterity: skill and ease of movement, especially of the hands; cleverness.",
    "Diatribe: an abusive, insulting verbal attack",
    "Didactic: intended for the purposes of moral teaching or instructing, even when such instruction is not necessary or welcome",
    "Dilate: to make larger; expand",
    "Diligent: continuously putting in great effort",
    "Disabuse: to free someone of believing something that is untrue",
    "Discern: to differentiate or distinguish; to perceive",
    "Disconcerting: unsettling",
    "Dislodge: to remove from a former position",
    "Disparity: the state of being different or unequal",
    "Disperse: to scatter or spread out",
    "Dissemble: to disguise or conceal",
    "Dissident: adj. disagreeable. n. one who disagrees",
    "Dissipate: to drive away; scatter",
    "Dissonance: lack of harmony; discord",
    "Diverge: to move apart, or extend in different directions; to differ in opinion.",
    "Divest: to get rid of",
    "Docile: easy to train or teach",
    "Dubious: unsure, skeptical",
    "Eccentric: adj. departing from convention. n. one who deviates from the norm.",
    "Eclectic: combining elements from many different sources or styles",
    "Effrontery: rude and presumptuous behavior",
    "Egregious: noticeably bad or offensive",
    "Eloquent: very clear and precise; quality of being skilled in clear and precise speech",
    "Elucidate: to clarify",
    "Emancipation: the act of freeing or liberating",
    "Emollient: adj. softening or soothing. n. a softening agent",
    "Empirical: based on or provable by observation and experiment",
    "Emulate: to follow an admirable example; imitate",
    "Endorse: to support or sign",
    "Engender: to give rise to; originate",
    "Entity: a discrete unit or being",
    "Enumerate: to state things in a list",
    "Ephemeral: temporary, fleeting",
    "Equivocal: uncertain or ambiguous",
    "Erudite: learned; having great knowledge",
    "Esoteric: understood by few people; mysterious",
    "Espouse: to choose to follow or support something",
    "Estimable: admirable; deserving of esteem",
    "Ethical: in line with the principles of right and wrong",
    "Euphemism: an inoffensive expression substituted for one that is deemed offensive",
    "Exacerbate: to intensify bitterness or violence",
    "Exceptional: having uncommonly great qualities",
    "Excoriate: to denounce; to chafe",
    "Exculpate: to remove blame; acquit",
    "Exhort: to urge or try to persuade",
    "Exigent: demanding immediate attention; urgent",
    "Explicate: to explain or make comprehensible",
    "Expunge: to get rid of or erase",
    "Extant: currently existing",
    "Extenuating: partially justifiable",
    "Extol: to praise or glorify",
    "Extrovert: a person characterized by concern with things outside of himself or herself; an outgoing or gregarious person",
    "Extricate: to free or disentangle",
    "Exultant: gleeful because of success",
    "Fallacy: an error in reasoning",
    "Familial: relating to the family",
    "Fathom: v. to come to understand the meaning of something. n. a measure of distance equal to six feet",
    "Fatuous: foolish or delusive; smug",
    "Feckless: lacking in purpose; careless",
    "Feign: to fabricate or deceive",
    "Feint: n. a deceptive, diversionary action. v. to make a deceptive show of.",
    "Fidelity: faithfulness or allegiance; often used to denote faithfulness in a romantic relationship, or faithfulness to a particular religion",
    "Florid: flushed with color; ornate",
    "Foil: to keep from being successful",
    "Foment: to incite or agitate",
    "Forage: to search for food or provisions",
    "Formidable: capable of arousing fear or awe",
    "Fortuitous: happening by accident or chance",
    "Forum: a public meeting place; a medium for open discussion",
    "Fracas: a noisy fight; a brawl",
    "Gainsay: to deny or contradict",
    "Garrison: a military post; the troops stationed at a military post.",
    "Garrulous: very talkative",
    "Genre: a type, class, or category",
    "Gist: main idea",
    "Glib: seemingly slick and clever, but lacking sincerity",
    "Gratuitous: for no reason or at no cost",
    "Gregarious: sociable; enjoying the company of others",
    "Grievous: causing grief or pain; serious",
    "Guile: cunning; shrewdness",
    "Hackneyed: unoriginal, overused",
    "Harrow: to torment or cause suffering and agony",
    "Hierarchy: a way to rank or place things in order",
    "Heterogeneous: made up of dissimilar elements; not homogeneous.",
    "Hypothesis: a tentative explanation that can be tested by further investigation and experimentation",
    "Idiosyncrasy: a peculiar characteristic",
    "Immutable: not subject to change",
    "Impending: threatening to occur",
    "Imperturbable: hard to excite or upset, very calm",
    "Impetus: a stimulus encouraging a particular activity",
    "Implosion: a violent, inward collapse",
    "Inadvertent: unintentional, often related to carelessness",
    "Inchoate: poorly formed or formless",
    "Incinerate: to set fire to and burn until reduced to ashes",
    "Incongruous: inconsistent; lacking in harmony",
    "Incorrigible: impossible to change or reform",
    "Indigenous: native; innate",
    "Inevitable: impossible to avoid; predictable",
    "Infer: to conclude from evidence",
    "Ingenuity: cleverness or imagination",
    "Inherent: naturally occurring, permanent element or attribute",
    "Inimical: harmful or unfriendly",
    "Innate: possessed at birth; a natural characteristic",
    "Inscrutable: difficult to understand; having an obscure nature",
    "Insinuate: to subtly imply or insert",
    "Insipid: dull; lacking in flavor or zest",
    "Insular: isolated; narrow-minded",
    "Integral: essential or necessary",
    "Intercede: to mediate, or plead on another’s behalf",
    "Interpolate: to insert or introduce between, often to falsify",
    "Intractable: difficult to manage; stubborn",
    "Inundate: to quickly overwhelm or exceed capacity",
    "Inure: to cause to accept something that is undesirable; habituate",
    "Invariable: not subject to question or change; constant",
    "Irascible: easily angered",
    "Jovial: full of joy and happiness",
    "Judicious: sensible, having good judgment",
    "Juxtapose: to place things next to each other in order to compare or contrast.",
    "Keen: quick-witted, sharp",
    "Kudos: praise for achievements",
    "Lambaste: to scold or criticize sharply; to beat",
    "Languish: to exist in a dreadful or gloomy situation; to become weak.",
    "Latter: the second of two things mentioned; nearer the end",
    "Laudable: deserving praise; favorable",
    "Lavish: adj. elaborate and luxurious. v. to freely and boundlessly bestow",
    "Lenient: easy-going, tolerant",
    "Lethargic: deficient in alertness; lacking energy",
    "Listless: characterized by a lack of energy",
    "Loathsome: offensive, disgusting",
    "Loquacious: very talkative or rambling",
    "Lucid: easily understood; clear",
    "Ludicrous: laughable or foolish",
    "Magnanimous: courageous, generous, or noble",
    "Malevolent: purposefully wishing harm on others",
    "Manifest: adj. clearly recognizable. v. to make clear. n. a list of transported goods or passengers used for record keeping",
    "Mar: to inflict damage or blemishes on",
    "Melancholy: adj. glum. n. deep contemplative thought",
    "Melodramatic: overly emotional or sentimental",
    "Mercurial: prone to sudden unpredictable change; volatile",
    "Metamorphosis: a transformation or change",
    "Meticulous: devoting a high amount of attention to detail",
    "Mettle: courage",
    "Minuscule: extremely small; unimportant",
    "Miscreant: villain; evildoer",
    "Mitigate: causing something to be less intense, forceful, or harmful",
    "Mollify: to calm down or alleviate; to soften",
    "Munificence: the act of liberally giving",
    "Nascent: just beginning to exist",
    "Negligent: characterized by carelessness and neglectfulness",
    "Negligible: meaningless and insignificant",
    "Nostalgia: a bittersweet longing for the past",
    "Noxious: unwholesome or harmful",
    "Obdurate: firm, stubborn",
    "Obscurity: the condition of being unknown",
    "Obsolete: no longer in use; outmoded or old-fashioned",
    "Obtuse: lacking intellectual clarity; blunt, or slow-witted",
    "Obviate: to render unnecessary",
    "Odious: arousing or deserving strong hatred",
    "Onerous: very troublesome or oppressively difficult",
    "Ostracize: to eliminate from a group",
    "Paradox: a self-contradiction; something that appears to be self-contradictory, but is nonetheless true",
    "Paragon: an example of excellence",
    "Parse: to break down into components",
    "Pedantic: characterized by a narrow concern for detail, particularly in academics.",
    "Penchant: a tendency or fondness",
    "Perceive: to become aware of something, usually through the senses.",
    "Percolate: to slowly pass through",
    "Peripatetic: adj. moving or traveling from place to place. n. one who travels frequently from place to place",
    "Periphery: the outermost boundary of an area",
    "Perjury: knowingly lying under oath",
    "Perpetuate: to prolong the existence or idea of; to make everlasting",
    "Pertinent: relevant or appropriate",
    "Peruse: to examine or review something",
    "Pervasive: capable of spreading or flowing throughout",
    "Phenomenon: observable fact or event; an unusual, significant, or outstanding occurrence. Plural is phenomena.",
    "Pith: significance, importance",
    "Placate: to calm",
    "Placid: calm or quiet",
    "Plagiarize: to copy another’s work and pretend that it is original",
    "Plausible: reasonable, likely",
    "Plethora: excess or overabundance",
    "Poignant: profoundly moving; incisive",
    "Polarity: the possession of two opposing attributes or ideas",
    "Postulate: to put forth or assert",
    "Pragmatic: practical",
    "Precarious: in a dangerous state, lacking security or stability",
    "Precedent: an example or event that is used to justify similar occurrences at a later time; custom arising from long-term practice",
    "Precept: a guiding rule or principle",
    "Precipitate: to cause something to happen very suddenly or prematurely",
    "Preclude: to prevent or make impossible",
    "Precursor: one that precedes or suggests the approach of another",
    "Presage: an omen or other warning sign",
    "Prescience: foresight; the power to see the future",
    "Presume: to take something for granted as being fact",
    "Prevaricate: to lie",
    "Probity: integrity and uprightness",
    "Prodigal: wasteful; extravagant",
    "Profuse: plentiful or abundant",
    "Progeny: offspring or product",
    "Prognosis: forecast or prediction",
    "Proliferate: to grow or increase rapidly",
    "Promulgate: to proclaim; usually in reference to rules or laws",
    "Propagate: to cause to multiply or spread",
    "Prototype: an original form of something",
    "Protract: to lengthen or prolong",
    "Prowess: great skill or ability in something",
    "Prudish: exaggeratedly proper; righteous",
    "Quaff: to drink heartily",
    "Querulous: characterized by constant complaining or whining",
    "Quixotic: unpredictable and impractical",
    "Quotidian: ordinary, occurring daily",
    "Rancor: bitter resentment",
    "Recalcitrant: stubbornly resistant; defiant",
    "Recluse: someone who is withdrawn from society",
    "Recompense: n. payment in return for something. v. to award compensation to",
    "Reconciliation: the reestablishing of cordial relations",
    "Recondite: difficult to understand",
    "Refute: to prove to be false; to deny the truth of",
    "Relegate: to refer or assign to a particular place or category",
    "Renounce: break; reject",
    "Reparation: compensation given to make amends",
    "Reproach: to express disapproval",
    "Repudiate: to reject or refuse as valid",
    "Resolute: definite, determined",
    "Resonant: strong and deep; lasting",
    "Resplendent: dazzling or brilliant in appearance",
    "Resurrect: to bring back to life",
    "Rhetoric: effective use of language; a style of speaking or writing",
    "Rigor: strictness or severity",
    "Sage: one revered for experience and wisdom",
    "Sanctimonious: feigning piety or righteousness",
    "Sanction: n. authoritative permission. v. to give official approval to",
    "Satirize: to insult using witty language",
    "Sedulous: persevering, industrious",
    "Skepticism: an attitude of doubt or disbelief",
    "Solace: comfort, safety",
    "Solicitous: concerned; thoughtful",
    "Specious: appearing to be true or genuine but actually deceptive",
    "Speculate: to theorize on the basis of inconclusive evidence",
    "Spontaneous: arising without apparent external cause; unrestrained",
    "Squelch: to crush or silence",
    "Stanch: to stop or check the flow of",
    "Static: fixed or stationary",
    "Stint: a length of time spent in a particular way",
    "Stoic: indifferent or unaffected",
    "Subjective: depending or based on someone’s personal attitudes or opinions",
    "Substantiate: to validate or support",
    "Subsume: to contain or include",
    "Subvert: to undermine, ruin, or overthrow",
    "Surfeit: an overabundance or excess",
    "Susceptible: easily influenced or likely to be affected",
    "Synchronized: occurring at the same time and at the same rate",
    "Tacit: using no words",
    "Temperance: moderation and self-restraint",
    "Tenuous: very thin or consisting of little substance",
    "Torpor: state of physical or mental sluggishness",
    "Tout: to promote or solicit",
    "Tractable: easy to control or work with",
    "Transcend: to go above and beyond; to rise above",
    "Transgress: to exceed or violate",
    "Transpose: to reverse the order of; interchange",
    "Unalloyed: pure; complete",
    "Unilaterally: performed in a one-sided manner",
    "Unprecedented: having no previous example",
    "Unstinting: very generous; bestowed liberally",
    "Urbanity: refinement and elegance",
    "Utilitarian: useful or practical",
    "Vacillate: to swing or waver",
    "Variegated: having a variety of colors or marks",
    "Vehement: forceful; displaying extreme emotion",
    "Venal: corruptible, open to bribery",
    "Venerable: highly esteemed or respected; commanding respect",
    "Veracity: truthfulness",
    "Verbose: wordy; long-winded",
    "Verisimilitude: the quality of appearing to be true or real",
    "Veritable: genuine or authentic",
    "Versatile: having many uses or a variety of abilities",
    "Vilify: to make negative statements about; to malign",
    "Vindicate: to clear someone or something from blame",
    "Virtually: in almost all instances; simulated as by a computer",
    "Vituperate: to criticize in an abusive way",
    "Voluminous: large in volume or bulk",
    "Voracious: excessively greedy; ravenous",
    "Wane: to gradually decrease",
    "Wary: cautious and untrusting",
    "Whet: to sharpen or stimulate",
    "Wily: very sly, deceptive",
    "Xenophobic: distrustful of strangers or foreign people",
    "Zealous: very passionate or enthusiastic",
    "Zenith: the peak point",
];

const length = sentences.length;

function myFunction() {
    const randomNumber = Math.floor(Math.random() * length);
    document.querySelector("#result").innerHTML = sentences[randomNumber];
    document.querySelector("#definition").innerHTML = definitions[randomNumber];
    document
        .querySelector("#definition")
        .classList.add("no-display-definition");
}
function showDef() {
    document
        .querySelector("#definition")
        .classList.remove("no-display-definition");
}
